version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Orders
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - ibmmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/reportes
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123
    networks:
      - backend

  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: reportes
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

volumes:
  mysql_data:
  mq_data:

networks:
  backend:
    driver: bridge
